### ISSUE TITLE
Question: why do we need to connect XS Classic artifacts in Neo through SAP Cloud Connector?

### ISSUE THREAD

**Issue by iamashokkumar** [SAP-samples/xsc-cap-migration#2]
Hi @LalithManokar,
QQ: why do we need to connect XS Classic artifacts in Neo (HANA in Neo is already in internet) through SAP Cloud Connector?

Background: I have an internal employee facing app (HANA XS Classic based) built several years in HANA in Neo that I want to migrate to SAP HANA Cloud as a CAP app in a CF subaccount.
BTW, can I use this migration tool for my scenario?

Thanks.
Ashok.

**Comment by gregorwolf** [comment]
I've asked the same question during the YouTube stream of the Devtoberfest session [Transforming legacy code to CAP with the help of GenAI](https://community.sap.com/t5/devtoberfest/transforming-legacy-code-to-cap-with-the-help-of-genai/ec-p/13856128#M724)

**Comment by LalithManokar** [comment]
@iamashokkumar @gregorwolfOur extension runs in the SAP Business Application Studio, which is part of SAP BTP. To access the XSC system located in either the NEO environment or on-premise, we need to set up a Cloud Connector and create a destination within the same BTP subaccount. This setup allows us to securely connect to the XSC system using a technical HANA user. We follow standard procedures and best practices to ensure a secure connection and access to design-time artifacts.
Regards,
Lalith. S

**Comment by gregorwolf** [comment]
Hi @LalithManokar,

the HANA in the Neo Environment is secured by TLS. That's why I don't understand what additional security Cloud Connector would add. It will still need to connect back to the Cloud hosted HANA.

Best Regards
Gregor

**Comment by LalithManokar** [comment]
Hi @gregorwolf 

"HANA databases within the SAP Neo environment are not accessible directly from outside Neo. To access them from on-premise systems or other cloud environments like SAP BTP Cloud Foundry, a database tunnel or SAP Cloud Connector must be used." https://community.sap.com/t5/technology-blogs-by-sap/sap-hana-2-0-on-neo-database-administration-using-on-premises-sap-hana/ba-p/13493787 section : Accessing HANA databases on Cloud. https://help.sap.com/docs/sap-hana-service-for-sap-btp-in-sap-and-microsoft-azure-regions/sap-hana-service-for-sap-btp-in-sap-regions/accessing-databases-remotely

Regards,
Lalith. S

**Comment by LalithManokar** [comment]
No Comments
